export {
  type ProductType,
  type ProductEntry,
  type SelectedServices,
  type ExtraCharge,
  type InternalNote,
  type CustomerNote,
  type PaymentStatus,
  type ShippingStatus,
  type BillingState,
  type LogisticsState,
  PAYMENT_STATUSES,
  SHIPPING_STATUSES,
  INITIAL_BILLING,
  INITIAL_LOGISTICS,
  genId,
  formatINR,
} from "@/lib/types";
